name: Build and Run Docker Container

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t windows-rdp-ngrok .

    - name: Run the Docker container
      run: docker run -d -p 3389:3389 windows-rdp-ngrok
