name: Ubuntu Desktop RDP

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ubuntu-desktop:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ubuntu-desktop:latest

    - name: Run Docker container
      run: |
        docker run -d --name ubuntu-desktop -p 3389:3389 ${{ secrets.DOCKER_USERNAME }}/ubuntu-desktop:latest
        sleep 30  # Wait for the container to be fully up

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvzf ngrok-v3-stable-linux-amd64.tgz

    - name: Start ngrok
      run: |
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 3389 &

    - name: Wait for ngrok to establish the tunnel
      run: |
        for i in {1..10}; do
          if curl --silent --show-error http://127.0.0.1:4040/api/tunnels; then
            break
          fi
          echo "Waiting for ngrok to start..."
          sleep 10
        done

    - name: Get ngrok public URL
      run: |
        curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'

    - name: Keep the workflow running for 6 hours
      run: |
        sleep 21600  # Sleep for 6 hours (21600 seconds)
